//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class CFiles : CForder
{
	private object -unsignet int SIZE
	{
		get;
		set;
	}

	private object Ext fileExt
	{
		get;
		set;
	}

	private object Data DataCreate
	{
		get;
		set;
	}

	public virtual void Ext getExt()
	{
		throw new System.NotImplementedException();
	}

	public virtual void void setExt(object Ext)
	{
		throw new System.NotImplementedException();
	}

	public virtual void unsignet int getSIZE()
	{
		throw new System.NotImplementedException();
	}

	public virtual void void setSIZE(object unsignet int SIZE)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Data getData()
	{
		throw new System.NotImplementedException();
	}

	public virtual void void setData(object Data DataGreate)
	{
		throw new System.NotImplementedException();
	}

}

